<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
 /** @var \Belluno\Magento2\Block\Checkout\Success $block*/
?>

<?php
$order = $block->getOrder();
$payment = $order->getPayment();
?>

<div class="belluno_success">
	<?php
	if($payment->getMethod() === 'bellunobankslip') :
		$digitable_line = $block->getBankSlipDigitableLine();
		$bankSlip = $block->getBankSlip();
	?>
		<div class="flex">
			<div class="linhes">
				<h3><?= __("Digitable Line") ?>:</h3>
				<div class="flex">
					<textarea readonly rows="1" name="pixer" id="select-this"> <?= $digitable_line ?> </textarea>
					<div class="actions-toolbar line-digitable">
						<div class="primary">
							<button id='clickMe'><?= __("Copy") ?></button>
						</div>
					</div>
				</div>
			</div>
		</div>
		<br>
		<div class="view-bankslip">
			<iframe src="<?= $bankSlip ?>" width="100%" height="500px"></iframe>
		</div>
		<br>
		<div class="primary">
			<a target="_blank" class="action primary continue" href="<?php echo $bankSlip; ?>"><span><?php echo __('View Bank Slip') ?></span></a>
		</div>
		<br>
	<?php endif ?>

	<?php
	if($payment->getMethod() === 'bellunopix') :
		$image = $block->getBase64Image();
		$copyPast = $block->getBase64Text();
	?>
		<br /><br />
		<div class="belluno_pix_valor_total">
			<h2><strong><?= __("Total") ?>: <span><?= $block->totalFormatted($order->getGrandTotal()) ?></span></strong></h2>
			<p><?= __("You will be notified by email after payment has been approved.") ?></p>
		</div>
		<div class="view-pix">
			<img src="data:image/png;base64,<?= $image ?>" width="30%" />
		</div>
		<br>
		<div class="container" style="max-width:60%;margin: 0 auto;">
			<div class="linhes">
				<h3><?= __("Copy and Paste") ?>:</h3>
				<div class="flex">
					<textarea readonly rows="3" name="pixer" id="select-this"> <?= base64_decode($copyPast) ?> </textarea>
					<div class="actions-toolbar line-digitable">
						<div class="primary">
							<button id='clickMe'><?= __("Copy") ?></button>
						</div>
					</div>
				</div>
			</div>
		</div>
		<br>
	<?php endif ?>
</div>