<?php
/** @var \Belluno\Magento2\Block\Order\Info $block */
$paymentInfo = $block->getPaymentInfo();
if($block->getPaymentMethod() === 'bellunobankslip'): ?>
	<button type="button" class="action primary btn-belluno-boleto" data-trigger="trigger">
		<span data-bind="i18n: '<?= $paymentInfo['text'] ?>'"></span>
	</button>
	<div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'modalClass': 'modalboleto',
            'title': 'Bank Slip',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
        }}">
		<div class="content">
			<input class="action primary btn-belluno-boleto" type="button" id="belluno" onclick="window.open('<?php echo $paymentInfo['url'] ?>');" value="<?= __("Download your ticket here") ?>" />
		</div>
		<h3><?= __("Digitable Line") ?>:</h3>
		<textarea readonly rows="1" name="pixer" id="select-this"><?= $paymentInfo['digitable_line'] ?></textarea>
		<div class="actions-toolbar">
			<div class="primary">
				<button id='clickMe'><?= __("Copy") ?></button>
			</div>
		</div>
	</div>
<?php endif; ?>

<?php if ($block->getPaymentMethod() === 'bellunopix'): ?>
	<button type="button" class="action primary btn-belluno-pix" data-trigger="trigger">
		<span data-bind="i18n: '<?= $paymentInfo['text'] ?>'"></span>
	</button>
	<div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'modalClass': 'modalpix',
            'title': 'Pix',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
        }}">
		<div class="content">
			<img src="data:image/png;base64,<?= $paymentInfo['base64_image'] ?>" width="30%" />
		</div>
		<h3><?= __("Copy and Paste") ?>:</h3>
		<textarea readonly rows="1" name="pixer" id="select-this"><?= base64_decode($paymentInfo['base64_text']) ?></textarea>
		<div class="actions-toolbar">
			<div class="primary">
				<button id='clickMe'><?= __("Copy") ?></button>
			</div>
		</div>
	</div>
<?php endif; ?>

<?php if ($block->getPaymentMethod() === 'bellunolink' && $paymentInfo['url'] !== false): ?>
	<button class="action primary btn-belluno-bellunolink" type="button" id="belluno" onclick="window.open('<?php echo $paymentInfo['url'] ?>');">
		<span data-bind="i18n: '<?= $paymentInfo['text'] ?>'"></span>
	</button>
<?php endif; ?>
